### ISSUE TITLE
WUFUC

### ISSUE THREAD

**Issue by iDolmatov** [git-coldsoft/WUFuC-Control-Panel#1]
Why the old version?

There is a newer version for both bit depths.
[wufuc_v1.0.1.201-a52637d4.zip](https://github.com/coldaes/WUFuC-Control-Panel/files/8694151/wufuc_v1.0.1.201-a52637d4.zip)
[wufuc_v1.0.1.201-x86+x64-MSI.zip](https://github.com/coldaes/WUFuC-Control-Panel/files/8694459/wufuc_v1.0.1.201-x86%2Bx64-MSI.zip)

**Comment by coldaes** [comment]
I was only able to find an older version of it since the original creator deleted the repo. Thank you, I will eventually include it in later updates.
